#! /bin/sh
# Copyright(c)'1994-2009 by The Givaro group
# This file is part of Givaro.
# Givaro is governed by the CeCILL-B license under French law
# and abiding by the rules of distribution of free software. 
# see the COPYRIGHT file for more details.


prefix=/usr/local
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib

major=`echo 4.0.4 | cut -d'.' -f1`
minor=`echo 4.0.4 | cut -d'.' -f2`
micro=`echo 4.0.4 | cut -d'.' -f3`
decvr=$((((($major*100)+$minor)*100)+$micro))


cflags=false
libs=false


usage()
{
    cat <<EOF
Usage: givaro-config [OPTION]

Known values for OPTION are:

  --prefix		show Givaro installation prefix 
  --libs		print library linking information
  --cflags		print pre-processor and compiler flags
  --help		display this help and exit
  --version		output version information string (eg 4.0.4)
  --decimal-version     output version information number (that is $decvr, also available in givconfig.h)

EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
    esac

    case "$1" in
    --prefix=*)
	prefix=$optarg
	;;

    --prefix)
	echo $prefix
	;;

    --version)
	echo 4.0.4
	exit 0
	;;

    --decimal-version)
	echo $decvr
	exit 0
	;;

    --help)
	usage 0
	;;

    --cflags)
       	echo -I${includedir} 
	;;

    --libs)
       	echo -L${libdir} -lgivaro  -lgmp -lgmpxx 
       	;;

    *)
	usage
	exit 1
	;;
    esac
    shift
done
echo

exit 0
